# Generated by Django 4.1 on 2022-08-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='vote',
            new_name='votes',
        ),
    ]
